### ISSUE TITLE
Give your strategy a cool or descriptive name

### ISSUE THREAD

**Issue by Catsuko** [Catsuko/ConnectFour#14]
Easy PR for your quota, give a cool name to SherryStrategy!

**Comment by Shewwiii** [comment]
How do I link this to a PR?

**Comment by mikepepping** [comment]
https://github.blog/2013-05-14-closing-issues-via-pull-requests/

put: fixes #14 in your PR 🐙🐙🐙

**Comment by Shewwiii** [comment]
@p3pping it didn't work 😭😭😭 why am i still open

**Comment by mikepepping** [comment]
Fixed by @Shewwiii
