### ISSUE TITLE
subsequent games in a round doesn't refresh the strategies

### ISSUE THREAD

**Issue by Shewwiii** [Catsuko/ConnectFour#27]
Is a problem when strategies contain saved variables

**Comment by Catsuko** [comment]
Two solutions come to my mind:

- A method on the strategy that will be called at the start of each game, strategies can then use it to reset variables as needed
- Just figure out a game has started in your strategy by checking the number of tokens placed in the board. If the 2d array contains 0-1 non-zero values then the game has just started!

**Comment by Catsuko** [comment]
After discussing, strategies will be responsible for managing their internal state including resetting when a new board is detected.
